Create load balancer
UgohDiegoKC/terraform-aws pull request #15
Opened 2022-10-06 13:21 UTC by UgohDiegoKC

2022-10-06 16:30 UTC, vladimirmukhin requested changes

2022-10-06 16:30 UTC, vladimirmukhin commented on level1/network.tf
> +  count = "${length(data.aws_availability_zones.available.names)}"
```suggestion
  count = length(data.aws_availability_zones.available.names)
```

2022-10-06 16:30 UTC, vladimirmukhin commented on level1/network.tf
> +  availability_zone = "${data.aws_availability_zones.available.names[0]}"
```suggestion
  availability_zone = data.aws_availability_zones.available.names[count.index]
```

2022-10-06 16:30 UTC, vladimirmukhin commented on level1/network.tf
> +  count = "${length(data.aws_availability_zones.available.names)}"
```suggestion
  count = length(data.aws_availability_zones.available.names)
```

2022-10-06 16:30 UTC, vladimirmukhin commented on level1/network.tf
> +  availability_zone = "${data.aws_availability_zones.available.names[1]}"
```suggestion
  availability_zone = data.aws_availability_zones.available.names[count.index]
```

2022-10-11 20:41 UTC, geoffrey1330 approved these changes

2022-10-12 04:04 UTC, merged